export default {
  Sunny: [
    "Keep your face to the sun and you will never see the shadows.",
    "Sunshine is the best medicine.",
    "Life is better when it's sunny outside.",
    "A day without sunshine is like, you know, night.",
    "Happiness is a sunny day.",
    "Sun is shining, the weather is sweet.",
    "Sunny days are the best days.",
    "Let the sunshine in and chase the clouds away.",
    "Sunny skies, happy hearts.",
    "Bask in the warmth of the sun's embrace.",
  ],
  "Partly Cloudy": [
    "Life is full of ups and downs, just like the weather.",
    "Even on a cloudy day, the sun is shining somewhere.",
    "Sometimes all you need are a few rays of hope.",
    "Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky.",
    "Embrace the beauty of a partly cloudy day.",
    "Every cloud has a silver lining.",
    "Gray skies are just nature's way of adding a little mystery to the day.",
    "Don't let a few clouds dampen your spirits.",
    "When life gives you partly cloudy skies, find a spot to watch the sunset.",
    "The sun and the clouds have an eternal dance in the sky.",
  ],
  Rainy: [
    "Let the rain wash away your worries.",
    "Life isn't about waiting for the storm to pass; it's about learning to dance in the rain.",
    "Rainy days are perfect for cozying up with a good book.",
    "Raindrops are like nature's confetti.",
    "Rain is just confetti from the sky.",
    "The best thing one can do when it's raining is to let it rain.",
    "Some people feel the rain, others just get wet.",
    "Rainy days make the flowers grow.",
    "There's something soothing about the sound of rain.",
    "Rain cleanses the soul as well as the earth.",
  ],
  "Mostly Sunny": [
    "Life is better when it's mostly sunny.",
    "Sunny moments make for the best memories.",
    "Find joy in the moments when the sun breaks through the clouds.",
    "Even on cloudy days, there's always a bit of sunshine.",
    "A mostly sunny day is a gift waiting to be unwrapped.",
    "Chase your dreams on the path of mostly sunny skies.",
    "When life hands you mostly sunny days, make the most of them.",
    "Brighten up your day with a dash of sunshine.",
    "A mostly sunny outlook leads to a brighter future.",
    "The sun never truly sets; it just shines a bit less sometimes.",
  ],
  Cloudy: [
    "Clouds may temporarily hide the sun, but they can't extinguish its light.",
    "Behind every cloud is another cloud.",
    "Cloudy days create the most beautiful sunsets.",
    "Even on cloudy days, there's a silver lining.",
    "Cloudy days make the sunny ones even sweeter.",
    "Clouds are like nature's artwork in the sky.",
    "Clouds are the sky's way of expressing its creativity.",
    "Don't let the clouds dampen your spirits.",
    "Clouds remind us that even the sky has its moods.",
    "Clouds may obscure the sun, but they can't dim its brilliance.",
  ],
};
